### ISSUE TITLE
Using 'rosidl_generate_dds_interfaces' cmake module does not generate any IDL file

### ISSUE THREAD

**Issue by TSC21** [ros2/rosidl_dds#48] opened 2018-12-16 22:26 UTC
**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - binaries
- DDS implementation:
  - Fast-RTPS

#### Steps to reproduce issue
Hi,

I am trying to use this package to generate DDS IDL files from ROS messages. I know that `rmw_fastrtps_cpp` is different since it uses introspection rather than generated code specific to each message so for FastRTPS, which results on one not having to generate `.idl` files. Though, for my particular case, I do require the IDL's to be generated in order to generate code for a micro-RTPS agent daemon.

The following snippet is what I am adding to the `CMakeLists.txt` file:
```cmake
rosidl_generate_dds_interfaces("${PROJECT_NAME}_fastrtps_idl"
  IDL_FILES ${MSGS}
  DEPENDENCY_PACKAGE_NAMES ${PROJECT_NAME} builtin_interfaces
  OUTPUT_SUBFOLDERS "dds_fastrtps"
)
```

Where `MSGS` are the list of ROS msgs inside `package_dir/msg`. I use `dds_fastrtps` since it's the same naming for the output folder of the OpenSplice IDL files.

#### Expected behavior
The expected behaviour, of course, is that the IDL files get generated, so they can be used.

#### Actual behavior
It's verified that `rosidl_generator_dds_idl__dds_fastrtps__arguments.json` is created under the build folder, though no `build/<project_name>/rosidl_generator_dds_idl/<project_name>/msg/dds_fastrpts` directory is created, which results on having an error on the install process:
```sh
CMake Error at ament_cmake_symlink_install/ament_cmake_symlink_install.cmake:158 (message):
  ament_cmake_symlink_install_files() can't find
  '/home/nuno/PX4/px4_ros_com_ros2/build/px4_ros_com/rosidl_generator_dds_idl/px4_ros_com/msg/dds_fastrtps/ActuatorArmed_.idl'
Call Stack (most recent call first):
  ament_cmake_symlink_install/ament_cmake_symlink_install.cmake:314 (ament_cmake_symlink_install_files)
  cmake_install.cmake:41 (include)


Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1
--- stderr: px4_ros_com
```

Thanks in advance for your support!

**Comment by TSC21** [comment] 2018-12-18 16:49
@nuclearsandwich @dirk-thomas can I get your feedback here? Thanks!

**Comment by nuclearsandwich** [comment] 2018-12-18 17:40
> Installation type:
>     * binaries

Are you referring here to the Debian packages or the provided archive builds? Bouncy or Crystal?

> I know that `rmw_fastrtps_cpp` is different since it uses introspection rather than generated code specific to each message so for FastRTPS

I'm not sure that this is still the case in Crystal. I thought that https://github.com/ros2/rmw_fastrtps/pull/218 switched rmw_fastrtps_cpp to default to static typesupport.

As far as the build error itself: I am not very familar with the IDL pipeline but if you share a link to the source for the package you're building I can try to reproduce the failure.

**Comment by TSC21** [comment] 2018-12-18 23:55
> Are you referring here to the Debian packages or the provided archive builds? Bouncy or Crystal?

Debian package for Bouncy.

> I'm not sure that this is still the case in Crystal. I thought that ros2/rmw_fastrtps#218 switched rmw_fastrtps_cpp to default to static typesupport.

I am using Bouncy it seems to be the case still.

> As far as the build error itself: I am not very familar with the IDL pipeline but if you share a link to the source for the package you're building I can try to reproduce the failure.

Sure thing: https://github.com/PX4/px4_ros_com. Though the above snippet needs to be added bellow https://github.com/PX4/px4_ros_com/blob/master/CMakeLists.txt#L48. The package does have `rosidl_generate_interfaces()` generating the IDL's for OpenSplice, but it's required it does it to Fast RTPS so one does not have the requirement for the opensplice rmw.

Thanks for the feedback and waiting for your testing results.

Note: a similar problem was reported in https://answers.ros.org/question/268396/ros2-generating-dds-idl-files-from-msg-ros-message-format/

**Comment by TSC21** [comment] 2018-12-19 08:53
@nuclearsandwich for a straightforward test and to reproduce:
1. Clone https://github.com/PX4/px4_ros_com to a ROS2 workspace;

2. Add:
```cmake
rosidl_generate_dds_interfaces("${PROJECT_NAME}_fastrtps_idl"
  IDL_FILES ${ROS_UORB_MSGS}
  DEPENDENCY_PACKAGE_NAMES ${PROJECT_NAME} builtin_interfaces
  OUTPUT_SUBFOLDERS "dds_fastrtps"
)
```
under https://github.com/PX4/px4_ros_com/blob/master/CMakeLists.txt#L48.

3. Build it using the `scripts/build_ros2_workspace.bash` script or manually using `colcon build --symlink-install --event-handlers console_direct+`.

4. After a while, and in the install process, you will get an error similar to the described.

**Comment by TSC21** [comment] 2018-12-22 00:12
@nuclearsandwich any inputs? Thanks!

**Comment by nuclearsandwich** [comment] 2018-12-22 01:02
Thanks for the reproduction steps @TSC21. Unfortunately I haven't yet had a chance to try them yet.

Off the top of my head I'm not sure that Bouncy generates IDL for Fast-RTPS under any circumstances. I believe your options will be to generate IDL from the OpenSplice or Connext RMW providers or try using Crystal and leveraging the static typesupport pipeline for Fast-RTPS.

**Comment by TSC21** [comment] 2018-12-22 12:16
> Thanks for the reproduction steps @TSC21. Unfortunately I haven't yet had a chance to try them yet.

No problem. Please, when you have time, try to reproduce it. I think it's critical to try to understand what's happening with `rosidl_generate_dds_interfaces()` CMake function. Thanks!

> Off the top of my head I'm not sure that Bouncy generates IDL for Fast-RTPS under any circumstances. I believe your options will be to generate IDL from the OpenSplice or Connext RMW providers or try using Crystal and leveraging the static typesupport pipeline for Fast-RTPS.

But wasn't `rosidl_generate_dds_interfaces()` supposed to generate IDL's for any DDS rmw? I was expecting this to be true for all releases by now. Why is it different from Bouncy to Crystal? Support Crystal, right now, is not in my plans. I just wanted to have the `rosidl_generate_dds_interfaces()` to do what it was meant for, as it doesn't seem to do it currently.

**Comment by dirk-thomas** [comment] 2018-12-26 20:38
> The following snippet is what I am adding to the `CMakeLists.txt` file:

The function `rosidl_generate_dds_interfaces` uses the CMake functions `add_custom_command` and `add_custom_target` internally. CMake will not invoke the command until you build a target which actually depends on the files declared as `OUTPUT` of the custom command or on the custom target. So you can't expect the function to "synchronously" create the `.idl` files for you if nothing needs t. Instead you need to make sure the target is actually being invoked. An example how an existing package does that: https://github.com/ros2/rosidl_typesupport_opensplice/blob/f6a985a1d406811806c5075aac8392e8d0ab06d5/rosidl_typesupport_opensplice_cpp/cmake/rosidl_typesupport_opensplice_cpp_generate_interfaces.cmake#L184-L187

> But wasn't `rosidl_generate_dds_interfaces()` supposed to generate IDL's for any DDS rmw?

No, unfortunately different vendors still require slightly different versions of `.idl` files due to their usage / support of special cases like pragmas, annotations etc. As a consequence each typesupport package which needs `.idl` files as input invokes this CMake function to generate `.idl` files only for its own consumption.

I will go ahead and close this ticket since the problem is in the way the function is being used. Please feel free to continue commenting.

**Closed as completed by dirk-thomas** 2018-12-26 20:38 UTC

**Comment by TSC21** [comment] 2018-12-31 12:02
@dirk-thomas thanks for the suggestion. I was able to generate the IDL files after setting up the proper dependencies of the target with respect to the IDL file list.

**Comment by TSC21** [comment] 2019-01-18 18:09
@dirk-thomas I know this issue is close but this is still a related question: I see that the `<package_name>_INTERFACE_FILES` macro is exported as CMake configuration extra. Though I can see that this only exports the the relative path of the msg/IDL files, while I would like to obtain the absolute path considering where the package is installed, so I can use them on another package. Is there a straight easy way of doing it? Or do I have to build an absolute path from `<package_name>_DIR`?
Thanks again

**Comment by dirk-thomas** [comment] 2019-01-18 18:15
> Or do I have to build an absolute path from `<package_name>_DIR`?

Yes, you should construct the absolute path based on this one.

**Comment by TSC21** [comment] 2019-01-18 19:34
Ok thanks found a solution by using `get_filename_component()`.
